// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

var listingsContainerStyles = {
  display: "flex",
  alignItems: "center",
  flexDirection: "row",
  flexWrap: "wrap",
  justifyContent: "space-evenly"
};

var imageBoxContainer = {
  height: "250px",
  width: "250px",
  objectFit: "cover"
};

var tagsListStyling = {
  display: "flex",
  listStyle: "none",
  alignItems: "center",
  flexDirection: "row",
  justifyContent: "space-around"
};

var listingBoxContainer = {
  borderStyle: "solid",
  borderWidth: "1px",
  margin: "10px",
  padding: "10px"
};

var listingsGroup = /* :: */[
  /* record */[
    /* title */"Nice Home Near De Anza",
    /* description */"A Lot of Cool Kids",
    /* tags : :: */[
      "social",
      /* :: */[
        "woke",
        /* :: */[
          "soy",
          /* [] */0
        ]
      ]
    ],
    /* photos : :: */[
      "https://www.deanza.edu/facilities/images/de-anza-pac-1024x512.jpg",
      /* [] */0
    ],
    /* landmarks : :: */[
      "The ATC",
      /* :: */[
        "Le Cafe",
        /* :: */[
          "Philz Coffee",
          /* [] */0
        ]
      ]
    ],
    /* address */"21250 Stevens Creek Blvd, Cupertino CA",
    /* currentNumberOfOcuppants */5,
    /* housePerks : :: */[
      "Sociable House",
      /* :: */[
        "Communal Fridge Fridays",
        /* :: */[
          "Shortest Commute Ever",
          /* [] */0
        ]
      ]
    ],
    /* monthlyRent */1350.60,
    /* estimatedMonthlyUtilities */0.0,
    /* homeApplicantRequirements */"A+ and Above Grades, Must Love Using Loftly! and needs to like the Golden State Warriors"
  ],
  /* :: */[
    /* record */[
      /* title */"Nice Home Near De Anza",
      /* description */"A Lot of Cool Kids",
      /* tags : :: */[
        "social",
        /* :: */[
          "woke",
          /* :: */[
            "soy",
            /* [] */0
          ]
        ]
      ],
      /* photos : :: */[
        "https://www.deanza.edu/facilities/images/de-anza-pac-1024x512.jpg",
        /* [] */0
      ],
      /* landmarks : :: */[
        "The ATC",
        /* :: */[
          "Le Cafe",
          /* :: */[
            "Philz Coffee",
            /* [] */0
          ]
        ]
      ],
      /* address */"21250 Stevens Creek Blvd, Cupertino CA",
      /* currentNumberOfOcuppants */5,
      /* housePerks : :: */[
        "Sociable House",
        /* :: */[
          "Communal Fridge Fridays",
          /* :: */[
            "Shortest Commute Ever",
            /* [] */0
          ]
        ]
      ],
      /* monthlyRent */1350.60,
      /* estimatedMonthlyUtilities */0.0,
      /* homeApplicantRequirements */"A+ and Above Grades, Must Love Using Loftly! and needs to like the Golden State Warriors"
    ],
    /* :: */[
      /* record */[
        /* title */"Nice Home Near De Anza",
        /* description */"A Lot of Cool Kids",
        /* tags : :: */[
          "social",
          /* :: */[
            "woke",
            /* :: */[
              "soy",
              /* [] */0
            ]
          ]
        ],
        /* photos : :: */[
          "https://www.deanza.edu/facilities/images/de-anza-pac-1024x512.jpg",
          /* [] */0
        ],
        /* landmarks : :: */[
          "The ATC",
          /* :: */[
            "Le Cafe",
            /* :: */[
              "Philz Coffee",
              /* [] */0
            ]
          ]
        ],
        /* address */"21250 Stevens Creek Blvd, Cupertino CA",
        /* currentNumberOfOcuppants */5,
        /* housePerks : :: */[
          "Sociable House",
          /* :: */[
            "Communal Fridge Fridays",
            /* :: */[
              "Shortest Commute Ever",
              /* [] */0
            ]
          ]
        ],
        /* monthlyRent */1350.60,
        /* estimatedMonthlyUtilities */0.0,
        /* homeApplicantRequirements */"A+ and Above Grades, Must Love Using Loftly! and needs to like the Golden State Warriors"
      ],
      /* :: */[
        /* record */[
          /* title */"Nice Home Near De Anza",
          /* description */"A Lot of Cool Kids",
          /* tags : :: */[
            "social",
            /* :: */[
              "woke",
              /* :: */[
                "soy",
                /* [] */0
              ]
            ]
          ],
          /* photos : :: */[
            "https://www.deanza.edu/facilities/images/de-anza-pac-1024x512.jpg",
            /* [] */0
          ],
          /* landmarks : :: */[
            "The ATC",
            /* :: */[
              "Le Cafe",
              /* :: */[
                "Philz Coffee",
                /* [] */0
              ]
            ]
          ],
          /* address */"21250 Stevens Creek Blvd, Cupertino CA",
          /* currentNumberOfOcuppants */5,
          /* housePerks : :: */[
            "Sociable House",
            /* :: */[
              "Communal Fridge Fridays",
              /* :: */[
                "Shortest Commute Ever",
                /* [] */0
              ]
            ]
          ],
          /* monthlyRent */1350.60,
          /* estimatedMonthlyUtilities */0.0,
          /* homeApplicantRequirements */"A+ and Above Grades, Must Love Using Loftly! and needs to like the Golden State Warriors"
        ],
        /* [] */0
      ]
    ]
  ]
];

function tagsMapProcessed(tags) {
  return List.mapi((function (index, tag) {
                return React.createElement("li", {
                            key: String(index)
                          }, React.createElement("p", undefined, tag));
              }), tags);
}

function landmarksMapProcessed(landmarks) {
  return List.mapi((function (index, tag) {
                return React.createElement("li", {
                            key: String(index)
                          }, React.createElement("p", undefined, tag));
              }), landmarks);
}

function housePerksMapProcessed(housePerks) {
  return List.mapi((function (index, tag) {
                return React.createElement("li", {
                            key: String(index)
                          }, React.createElement("p", undefined, tag));
              }), housePerks);
}

var listingsProcessed = List.mapi((function (index, listing) {
        return React.createElement("div", {
                    key: String(index),
                    style: listingBoxContainer
                  }, React.createElement("h2", undefined, listing[/* title */0]), React.createElement("img", {
                        style: imageBoxContainer,
                        src: List.hd(listing[/* photos */3])
                      }), React.createElement("div", undefined, React.createElement("p", undefined, listing[/* address */5]), React.createElement("p", undefined, "Current Occupants: " + String(listing[/* currentNumberOfOcuppants */6])), React.createElement("p", undefined, "Monthly Rent: " + listing[/* monthlyRent */8].toString()), React.createElement("p", undefined, "Estimated Monthly Utilities: " + listing[/* estimatedMonthlyUtilities */9].toString())), React.createElement("h3", undefined, "Description"), React.createElement("p", undefined, listing[/* description */1]), React.createElement("h3", undefined, "Applicant Requirements"), React.createElement("p", undefined, listing[/* homeApplicantRequirements */10]), React.createElement("div", undefined, React.createElement("p", undefined, "tags: "), React.createElement("ul", {
                            style: tagsListStyling
                          }, $$Array.of_list(tagsMapProcessed(listing[/* tags */2])))), React.createElement("div", undefined, React.createElement("p", undefined, "landmarks: "), React.createElement("ul", {
                            style: tagsListStyling
                          }, $$Array.of_list(landmarksMapProcessed(listing[/* landmarks */4])))), React.createElement("div", undefined, React.createElement("p", undefined, "house perks: "), React.createElement("ul", {
                            style: tagsListStyling
                          }, $$Array.of_list(housePerksMapProcessed(listing[/* housePerks */7])))));
      }), listingsGroup);

function RoomMateMatch(Props, _children) {
  var name = Props.name;
  var match = React.useState((function () {
          return 0;
        }));
  var setCount = match[1];
  var count = match[0];
  var match$1 = React.useState((function () {
          return false;
        }));
  var setFoo = match$1[1];
  React.useEffect((function () {
          console.log("Hello UseEffect Reason!");
          Curry._1(setFoo, (function (param) {
                  return true;
                }));
          return ;
        }), /* array */[setFoo]);
  return React.createElement(React.Fragment, {
              children: null
            }, React.createElement("h1", undefined, "Future Roommate Listings"), React.createElement("p", undefined, "This page was developed with Reason and React this allows for strict types and better type inferences."), React.createElement("p", undefined, name + (" clicked " + (String(count) + " times"))), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(setCount, (function (param) {
                                    return count + 1 | 0;
                                  }));
                    })
                }, "Click me"), React.createElement("div", {
                  style: listingsContainerStyles
                }, $$Array.of_list(listingsProcessed)));
}

var make = RoomMateMatch;

export {
  listingsContainerStyles ,
  imageBoxContainer ,
  tagsListStyling ,
  listingBoxContainer ,
  listingsGroup ,
  tagsMapProcessed ,
  landmarksMapProcessed ,
  housePerksMapProcessed ,
  listingsProcessed ,
  make ,
  
}
/* listingsProcessed Not a pure module */
