// Generated by ReScript, PLEASE EDIT WITH CARE


function ix(filename) {
  return "/" + filename;
}

function mxref(filename) {
  return "/markdown/" + filename;
}

export {
  ix ,
  mxref ,
  
}
/* No side effect */
