// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function ExampleReason(Props, _children) {
  var name = Props.name;
  var match = React.useState((function () {
          return 0;
        }));
  var setCount = match[1];
  var count = match[0];
  var match$1 = React.useState((function () {
          return false;
        }));
  var setFoo = match$1[1];
  React.useEffect((function () {
          console.log("Hello UseEffect Reason!");
          Curry._1(setFoo, (function (param) {
                  return true;
                }));
          return ;
        }), ([]));
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Future Roommate Listings"), React.createElement("p", undefined, "This page was developed with Reason and React this allows for strict types and better type inferences."), React.createElement("p", undefined, name + (" clicked " + (String(count) + " times"))), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(setCount, (function (param) {
                                    return count + 1 | 0;
                                  }));
                    })
                }, "Click me"));
}

var make = ExampleReason;

export {
  make ,
  
}
/* react Not a pure module */
